const fs = require('fs');
const path = require('path');

const rootDir = __dirname;
const docFile = path.join(rootDir, 'DOCUMENTATION.md');
const readmeFile = path.join(rootDir, 'README.md');
const backendFile = path.join(rootDir, 'BACKEND.md');

// 1. Read README.md
let readmeContent = '';
if (fs.existsSync(readmeFile)) {
  readmeContent = fs.readFileSync(readmeFile, 'utf8');
}

// 2. Extract API Reference from DOCUMENTATION.md
let apiContent = '';
if (fs.existsSync(docFile)) {
  const docText = fs.readFileSync(docFile, 'utf8');
  
  // Try to find API_REFERENCE
  const startIndex = docText.indexOf('## Source: docs/API_REFERENCE.md');
  const endIndex = docText.indexOf('## Source: docs/ARCHITECTURE.md', startIndex);
  
  if (startIndex !== -1 && endIndex !== -1) {
    apiContent = docText.substring(startIndex, endIndex);
  }
}

// 3. Read config docs
const configPaths = [
  'backend/docs/architecture/configuration-management.md',
  'backend/docs/runbooks/configuration-management.md'
];

let configContent = '## Configuration Guide\n\n';
for (const cp of configPaths) {
  const fullPath = path.join(rootDir, cp);
  if (fs.existsSync(fullPath)) {
    configContent += fs.readFileSync(fullPath, 'utf8') + '\n\n';
  }
}

// 4. Merge all together
let merged = `<!-- BACKEND.md generated by consolidation script -->\n\n`;
merged += readmeContent + '\n\n';
merged += configContent + '\n\n';
merged += '## API Documentation\n\n';
merged += apiContent.replace('## Source: docs/API_REFERENCE.md', '') + '\n\n';

fs.writeFileSync(backendFile, merged);
console.log('BACKEND.md created successfully.');

// 5. Delete old files
if (fs.existsSync(readmeFile)) {
    fs.unlinkSync(readmeFile);
    console.log('Deleted README.md');
}

for (const cp of configPaths) {
  const fullPath = path.join(rootDir, cp);
  if (fs.existsSync(fullPath)) {
    fs.unlinkSync(fullPath);
    console.log('Deleted ' + cp);
  }
}
